### PR TITLE
(Temporary) Use InMemory stores for anonymous tokens to support current stage on App

### PR DESCRIPTION
**Pull request by jhannes**
This change in necessary for the current code of the corresponding branch in Fhi.Smittestopp.App to work. It will be updated with new keys as soon as we have support for this.

The branch also contains updated instructions in the README.md file.

### CODE REVIEW

**Comment by sindremb** [comment]
@jhannes Is it safe to discard the conflicting change to appsettings.Development.json in this PR?

**Comment by jhannes** [comment]
> @jhannes Is it safe to discard the conflicting change to appsettings.Development.json in this PR?

`certId` or `signing` fingerprint? Yes, it can be discarded. This was an accident. (Ideally, this value should be in a `.gitignore`-ed file to avoid commit wars)

**Comment by sindremb** [comment]
@jhannes Ok, I can fix the conflict then. One option to override the thumbprint for your local env could be to use

`dotnet user-secrets set "signingCredentials:anonymousTokens:certId" "<your-thumbprint>"`

However, that could become confusing if you forget, and later wonder where the value comes from.

**Comment by jhannes** [comment]
> @jhannes Ok, I can fix the conflict then. One option to override the thumbprint for your local env could be to use
> 
> `dotnet user-secrets set "signingCredentials:anonymousTokens:certId" "<your-thumbprint>"`
> 
> However, that could become confusing if you forget, and later wonder where the value comes from.

I like this. It seems like all computer-specific information can be put into `dotnet user-secrets`. This would a good one-stop-shop. So the principles of configuration:

* As much as possible should be non-varying, possibly hard-coded
* What shouldn't be hard-coded should preferably be in applsettings.json
* What's specific per environment should be minimized and kept in appsettings.<environment>.json
* What's specific per machine should be in dotnet secrets

**Pull request merged**
